### ISSUE TITLE
Build Roaring Fork Technologists website

### ISSUE THREAD

**Issue by justinlewis** [COWestSlopeTech/westslopetech#1]
We should do a website. Let's start with some basic planning:

- [x] Get the domain (roaringforktechnologists.com)
- [x] Decide on a platform (I'm really partial to Jekyll but we should discuss)
- [x] Assemble basic requirements - Ticket #4 
- [x] Decide on starting point theme - Ticket #2 
- [x] Mock up (super casually) a layout and general design - Ticket #6
- [x] Draft basic content - Tickets #5 
- [ ] Basic branding (logo) - Ticket #3 
- [ ] Put all the pieces together
- [ ] Deploy
